# Generated by Django 5.0.1 on 2025-10-02 00:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0021_studentgroup_is_free"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="prepaid_balance",
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="رصيد الطالب في الفوج",
            ),
        ),
    ]
