# Generated by Django 5.0.1 on 2025-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0021_studentgroup_is_free"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="remaining_sessions",
            field=models.IntegerField(default=0, verbose_name="الحصص المتبقية"),
        ),
    ]
