# Generated by Django 5.0.1 on 2025-10-01 03:24

from django.db import migrations
from decimal import Decimal
import math

def populate_remaining_sessions(apps, schema_editor):
    Student = apps.get_model('school_app', 'Student')
    StudentGroup = apps.get_model('school_app', 'StudentGroup')

    for student in Student.objects.filter(prepaid_balance__gt=0):
        student_groups = student.studentgroup_set.all()
        num_groups = student_groups.count()

        if num_groups > 0:
            balance_per_group = student.prepaid_balance / num_groups
            for student_group in student_groups:
                price_per_4 = student_group.group.price_per_4_sessions
                if price_per_4 and price_per_4 > 0:
                    price_per_session = price_per_4 / Decimal('4.0')
                    if price_per_session > 0:
                        sessions_to_add = math.floor(balance_per_group / price_per_session)
                        student_group.remaining_sessions = sessions_to_add
                        student_group.save()

def reverse_code(apps, schema_editor):
    # This is a one-way data migration. If we need to reverse, we'd need to store the original balances somewhere.
    # For now, we'll just accept that this is not perfectly reversible.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0022_studentgroup_remaining_sessions'),
    ]

    operations = [
        migrations.RunPython(populate_remaining_sessions, reverse_code=reverse_code),
    ]
