# Generated by Django 5.0.1 on 2025-10-01 15:39
import math
from decimal import Decimal
from django.db import migrations


def migrate_prepaid_balance_to_sessions(apps, schema_editor):
    Student = apps.get_model('school_app', 'Student')
    StudentGroup = apps.get_model('school_app', 'StudentGroup')

    # Process students with a balance
    for student in Student.objects.filter(prepaid_balance__gt=0):
        student_groups = student.studentgroup_set.all().select_related('group')

        first_valid_group_found = False

        # Iterate to find the first group to transfer the balance to
        for sg in student_groups:
            # Check if this group can be used for balance transfer and if we haven't transferred yet
            if not first_valid_group_found and sg.group.price_per_4_sessions and sg.group.price_per_4_sessions > 0:
                price_per_session = sg.group.price_per_4_sessions / Decimal('4.0')
                if price_per_session > 0:
                    num_sessions = math.floor(student.prepaid_balance / price_per_session)
                    sg.remaining_sessions = num_sessions
                    sg.save()
                    first_valid_group_found = True
                else:
                    # Price is zero or negative, so it's not a valid group for transfer
                    sg.remaining_sessions = 0
                    sg.save()
            else:
                # This group is not the first valid one, so it gets 0 sessions
                sg.remaining_sessions = 0
                sg.save()

        # After iterating through all groups, zero out the student's old balance
        student.prepaid_balance = Decimal('0.00')
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0022_studentgroup_remaining_sessions"),
    ]

    operations = [
        migrations.RunPython(migrate_prepaid_balance_to_sessions, migrations.RunPython.noop),
    ]
