# Generated by Django 5.0.1 on 2025-10-02 13:24

from django.db import migrations
from decimal import Decimal

def zero_out_prepaid_balances(apps, schema_editor):
    """
    Sets the prepaid_balance of all existing students to 0.
    """
    Student = apps.get_model("school_app", "Student")
    Student.objects.all().update(prepaid_balance=Decimal('0.00'))

def revert_zero_out(apps, schema_editor):
    """
    This is a one-way data migration. No action is taken on reverse.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0022_studentgroup_balance"),
    ]

    operations = [
        migrations.RunPython(zero_out_prepaid_balances, reverse_code=revert_zero_out),
    ]
