# Generated by Django 5.0.1 on 2025-10-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0023_auto_20251001_1539"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="prepaid_balance",
        ),
    ]
