# Generated by Django 5.0.1 on 2025-10-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0023_populate_remaining_sessions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="prepaid_balance",
        ),
    ]
