# Generated by Django 5.0.1 on 2025-10-02 15:17

from django.db import migrations

def update_academic_levels(apps, schema_editor):
    AcademicLevel = apps.get_model('school_app', 'AcademicLevel')
    Student = apps.get_model('school_app', 'Student')
    Group = apps.get_model('school_app', 'Group')

    # Create new levels
    sci_level, _ = AcademicLevel.objects.update_or_create(
        name="السنة اولى علمي", category="HIGH", defaults={'name': "السنة اولى علمي"}
    )
    lit_level, _ = AcademicLevel.objects.update_or_create(
        name="السنة اولى ادبي", category="HIGH", defaults={'name': "السنة اولى ادبي"}
    )

    # Find and update from the old level
    try:
        old_level = AcademicLevel.objects.get(name="السنة الأولى المشتركة", category="HIGH")

        # Update students
        Student.objects.filter(academic_level=old_level).update(academic_level=sci_level)

        # Update groups
        for group in Group.objects.filter(academic_levels=old_level):
            group.academic_levels.remove(old_level)
            group.academic_levels.add(sci_level)

        # Delete the old level
        old_level.delete()
    except AcademicLevel.DoesNotExist:
        # If the old level doesn't exist, there's nothing to migrate
        pass

def revert_academic_levels(apps, schema_editor):
    AcademicLevel = apps.get_model('school_app', 'AcademicLevel')
    Student = apps.get_model('school_app', 'Student')
    Group = apps.get_model('school_app', 'Group')

    # Re-create the old level
    old_level, _ = AcademicLevel.objects.update_or_create(
        name="السنة الأولى المشتركة", category="HIGH", defaults={'name': "السنة الأولى المشتركة"}
    )

    try:
        sci_level = AcademicLevel.objects.get(name="السنة اولى علمي", category="HIGH")

        # Revert students
        Student.objects.filter(academic_level=sci_level).update(academic_level=old_level)

        # Revert groups
        for group in Group.objects.filter(academic_levels=sci_level):
            group.academic_levels.remove(sci_level)
            group.academic_levels.add(old_level)

        sci_level.delete()
    except AcademicLevel.DoesNotExist:
        pass

    try:
        lit_level = AcademicLevel.objects.get(name="السنة اولى ادبي", category="HIGH")
        lit_level.delete()
    except AcademicLevel.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0024_remove_student_prepaid_balance"),
    ]

    operations = [
        migrations.RunPython(update_academic_levels, reverse_code=revert_academic_levels),
    ]
